from django.conf.urls import patterns, include, url
from django.contrib import admin
from onadata.apps.fao_module import views

urlpatterns = patterns('',

                       url(r'^add_patients_disease_file_form/$', views.add_patients_disease_file_form,
                           name='add_patients_disease_file_form'),
                       url(r'^insert_patients_disease_file_form/$', views.insert_patients_disease_file_form,
                           name='insert_patients_disease_file_form'),
                       url(r'^add_patients_symptoms_file_form/$', views.add_patients_symptoms_file_form,
                           name='add_patients_symptoms_file_form'),
                       url(r'^insert_patients_symptoms_file_form/$', views.insert_patients_symptoms_file_form,
                           name='insert_patients_symptoms_file_form'),
                       url(r'^add_medicine_list_file_form/$', views.add_medicine_list_file_form,
                           name='add_medicine_list_file_form'),
                       url(r'^insert_medicine_list_file_form/$', views.insert_medicine_list_file_form,
                           name='insert_medicine_list_file_form'),
                       url(r'^insert_medicine_list_form/$', views.insert_medicine_list_form,
                           name='insert_medicine_list_form'),
                       url(r'^medicine_list/$', views.medicine_list, name='medicine_list'),
                       url(r'^edit_medicine_list_form/(?P<medicine_id>\d+)/$', views.edit_medicine_list_form,
                           name='edit_medicine_list_form'),
                       url(r'^update_medicine_list_form/$', views.update_medicine_list_form,
                           name='update_medicine_list_form'),
                       url(r'^delete_medicine_list_form/(?P<medicine_id>\d+)/$', views.delete_medicine_list_form,
                           name='delete_medicine_list_form'),
                       url(r'^designations_list/$', views.designations_list, name='designations_list'),
                       url(r'^add_designations_form/$', views.add_designations_form, name='add_designations_form'),
                       url(r'^insert_designations_form/$', views.insert_designations_form,
                           name='insert_designations_form'),
                       url(r'^edit_designations_form/(?P<designations_id>\d+)/$', views.edit_designations_form,
                           name='edit_designations_form'),
                       url(r'^update_designations_form/$', views.update_designations_form,
                           name='update_designations_form'),
                       url(r'^getDistricts/$', views.getDistricts, name='getDistricts'),
                       url(r'^getUpazilas/$', views.getUpazilas, name='getUpazilas'),
                       url(r'^add_disaster_file_form/$', views.add_disaster_file_form, name='add_disaster_file_form'),

                       url(r'^disease_list/$', views.disease_list, name='disease_list'),
                       url(r'^insert_patients_disease_form/$', views.insert_patients_disease_form,
                           name='insert_patients_disease_form'),
                       url(r'^edit_disease_list_form/(?P<disease_id>\d+)/$', views.edit_disease_list_form,
                           name='edit_disease_list_form'),
                       url(r'^update_disease_list_form/$', views.update_disease_list_form,
                           name='update_disease_list_form'),
                        url(r'^delete_disease_list_form/(?P<disease_id>\d+)/$', views.delete_disease_list_form,
                           name='delete_disease_list_form'),

                       url(r'^user_resource_map_list/$', views.user_resource_map_list, name='user_resource_map_list'),
                       url(r'^load_user_resource_data/$', views.load_user_resource_data,
                           name='load_user_resource_data'),
                       url(r'^designation_resource_map_list/$', views.designation_resource_map_list, name='designation_resource_map_list'),

			#url(r'^affected_area/$', views.affected_area,name='affected_area'),
                    	url(r'^json_data_fetch/$', views.json_data_fetch,name='json_data_fetch'),
                	url(r'^disease_stat_chart/$', views.disease_stat_chart,name='disease_stat_chart'),
                      url(r'^symptom_list/$', views.symptom_list, name='symptom_list'),
                      url(r'^insert_patients_symptom_form/$', views.insert_patients_symptom_form,
                           name='insert_patients_symptom_form'),
                      url(r'^edit_symptom_list_form/(?P<symptom_id>\d+)/$', views.edit_symptom_list_form,
                           name='edit_symptom_list_form'),
                      url(r'^update_symptom_list_form/$', views.update_symptom_list_form,
                           name='update_symptom_list_form'),
                      url(r'^delete_symptom_list_form/(?P<symptom_id>\d+)/$', views.delete_symptom_list_form,
                           name='delete_symptom_list_form'),





                      url(r'^farm_assessment_list/$', views.farm_assessment_list, name='farm_assessment_list'),
                       url(r'^xls_report_creator_for_farm_assessment/$', views.xls_report_creator_for_farm_assessment,
                           name='xls_report_creator_for_farm_assessment'),
                       url(r'^avian_influenza_list/$', views.avian_influenza_list, name='avian_influenza_list'),
                       url(r'^xls_report_creator_for_avian_influenza/$', views.xls_report_creator_for_avian_influenza,
                           name='xls_report_creator_for_avian_influenza'),
                       url(r'^patient_registry_list/$', views.patient_registry_list, name='patient_registry_list'),
                       url(r'^xls_report_creator_for_patient_registry/$', views.xls_report_creator_for_patient_registry,
                           name='xls_report_creator_for_patient_registry'),
                       url(r'^postmortem_list/$', views.postmortem_list, name='postmortem_list'),
                       url(r'^xls_report_creator_for_postmortem/$', views.xls_report_creator_for_postmortem,
                           name='xls_report_creator_for_postmortem'),
                       url(r'^generic_disease_investigation_list/$', views.generic_disease_investigation_list,
                           name='generic_disease_investigation_list'),
                       url(r'^xls_report_creator_for_generic_disease_investigation/$',
                           views.xls_report_creator_for_generic_disease_investigation,
                           name='xls_report_creator_for_generic_disease_investigation'),
                       url(r'^avian_influenza_investigation_list/$', views.avian_influenza_investigation_list,
                           name='avian_influenza_investigation_list'),
                       url(r'^xls_report_creator_for_avian_influenza_investigation/$',
                           views.xls_report_creator_for_avian_influenza_investigation,
                           name='xls_report_creator_for_avian_influenza_investigation'),
                       url(r'^sink_surveillance_list/$', views.sink_surveillance_list, name='sink_surveillance_list'),
                       url(r'^xls_report_creator_for_sink_surveillance/$',
                           views.xls_report_creator_for_sink_surveillance,
                           name='xls_report_creator_for_sink_surveillance'),
                       url(r'^sink_surveillance_view/(?P<data_id>\d+)/$', views.sink_surveillance_view,
                           name='sink_surveillance_view'),
                        url(r'^pathology_list/$', views.pathology_list, name='pathology_list'),
                        url(r'^xls_report_creator_for_pathology/$', views.xls_report_creator_for_pathology,
                           name='xls_report_creator_for_pathology'),

                        url(r'^avian_influenza_view/(?P<data_id>\d+)/$', views.avian_influenza_view,
                           name='avian_influenza_view'),
                       url(r'^avian_influenza_investigation_view/(?P<data_id>\d+)/$',
                           views.avian_influenza_investigation_view,
                           name='avian_influenza_investigation_view'),
                       url(r'^generic_disease_investigation_view/(?P<data_id>\d+)/$',
                           views.generic_disease_investigation_view,
                           name='generic_disease_investigation_view'),
                       url(r'^farm_assessment_view/(?P<data_id>\d+)/$',
                           views.farm_assessment_view,
                           name='farm_assessment_view'),
                       url(r'^patient_registry_view/(?P<data_id>\d+)/$',
                           views.patient_registry_view,
                           name='patient_registry_view'),
                       url(r'^postmortem_view/(?P<data_id>\d+)/$',
                           views.postmortem_view,
                           name='postmortem_view'),
                       url(r'^pathology_view/(?P<data_id>\d+)/$',
                           views.pathology_view,
                           name='pathology_view'),

                       url(r'^ai_lab_result_list/$', views.ai_lab_result_list, name='ai_lab_result_list'),
                       url(r'^xls_report_creator_for_ai_lab_result/$', views.xls_report_creator_for_ai_lab_result,
                           name='xls_report_creator_for_ai_lab_result'),
                       url(r'^sink_lab_result_list/$', views.sink_lab_result_list, name='sink_lab_result_list'),
                       url(r'^xls_report_creator_for_sink_lab_result/$', views.xls_report_creator_for_sink_lab_result,
                           name='xls_report_creator_for_sink_lab_result'),

                        url(r'^affected_area_mortaility/$', views.affected_area_mortaility,
                           name='affected_area_mortaility'),
                       url(r'^json_data_fetch_mortaility/$', views.json_data_fetch_mortaility,
                           name='json_data_fetch_mortaility'),
                       url(r'^affected_area_affect/$', views.affected_area_affect, name='affected_area_affect'),
                       url(r'^json_data_fetch_affect/$', views.json_data_fetch_affect, name='json_data_fetch_affect'),  

                      # url(r'^home_page/$', views.home_page,name='home_page'),

                        url(r'^livebird_markets_list/$', views.livebird_markets_list, name='livebird_markets_list'),
                       url(r'^add_livebird_markets_list_file_form/$', views.add_livebird_markets_list_file_form,
                           name='add_livebird_markets_list_file_form'),
                       url(r'^insert_livebird_markets_list_file_form/$', views.insert_livebird_markets_list_file_form,
                           name='insert_livebird_markets_list_file_form'),
                       url(r'^insert_livebird_markets_list_form/$', views.insert_livebird_markets_list_form,
                           name='insert_livebird_markets_list_form'),
                       url(r'^edit_livebird_markets_list_form/(?P<livebird_markets_id>\d+)/$',
                           views.edit_livebird_markets_list_form, name='edit_livebird_markets_list_form'),
                       url(r'^update_livebird_markets_form/$', views.update_livebird_markets_form,
                           name='update_livebird_markets_form'),
                       url(r'^delete_livebird_markets_list_form/(?P<livebird_markets_id>\d+)/$',
                           views.delete_livebird_markets_list_form, name='delete_livebird_markets_list_form'),

                       url(r'^export_all/$',views.export_all, name='export_all'),


                       url(r'^participatory_livestock_assessment_list/$', views.participatory_livestock_assessment_list, name='participatory_livestock_assessment_list'),
                       url(r'^xls_report_creator_for_participatory_livestock_assessment/$', views.xls_report_creator_for_participatory_livestock_assessment,
                           name='xls_report_creator_for_participatory_livestock_assessment'),
                       url(r'^submission_count_list/$', views.submission_count_list, name='submission_count_list'),
                       url(r'^hr_engagement_list/$', views.hr_engagement_list, name='hr_engagement_list'),
                       url(r'^getCountData/$', views.getCountData, name='getCountData'),
                       url(r'^getHRData/$', views.getHRData, name='getHRData'),
                       ################################################
                       ###############################################

                       )
